In [9]:
import pandas as pd
import numpy as np

In [10]:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')

In [11]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [12]:
n_users = ratings.user_id.unique().shape[0]
n_items = ratings.movie_id.unique().shape[0]

In [13]:
print("The number of user:",n_users)
print("The number of n_items:",n_items)

The number of user: 943
The number of n_items: 1682

In [14]:
data=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')

In [15]:
data

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data_matrix=data.replace(np.nan,0)

In [17]:
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
from sklearn.metrics.pairwise import pairwise_distances 
user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [19]:
item_similarity

array([[0.00000000e+00, 5.97617822e-01, 6.69755213e-01, ...,
        1.00000000e+00, 9.52816933e-01, 9.52816933e-01],
       [5.97617822e-01, 0.00000000e+00, 7.26930825e-01, ...,
        1.00000000e+00, 9.21700637e-01, 9.21700637e-01],
       [6.69755213e-01, 7.26930825e-01, 2.22044605e-16, ...,
        1.00000000e+00, 1.00000000e+00, 9.03124947e-01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 9.03124947e-01, ...,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00]],
      shape=(1682, 1682))

In [20]:
def predict(ratings, similarity, type='user'):
    ratings = np.asarray(ratings)

    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)

        ratings_diff = ratings - mean_user_rating[:, np.newaxis]

        pred = (
            mean_user_rating[:, np.newaxis]
            + similarity.dot(ratings_diff)
            / np.array([np.abs(similarity).sum(axis=1)]).T
        )

    elif type == 'item':
        pred = (
            ratings.dot(similarity)
            / np.array([np.abs(similarity).sum(axis=1)])
        )

    return pred

In [21]:
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

In [22]:
user_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]], shape=(943, 1682))

In [30]:
input_item=34

In [31]:
item_sim_table=pd.DataFrame(item_similarity)

In [32]:
item_sim_table

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.000000,0.597618,6.697552e-01,0.545062,0.713286,0.883656,0.379021,0.518886,0.503712,0.726065,...,0.964613,1.0,1.000000,1.000000,0.964613,1.0,1.0,1.0,0.952817,0.952817
1,0.597618,0.000000,7.269308e-01,0.497429,0.681164,0.916437,0.616597,0.662998,0.744748,0.828918,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.921701,0.921701
2,0.669755,0.726931,2.220446e-16,0.675134,0.787043,0.893278,0.627079,0.799206,0.726331,0.841896,...,1.000000,1.0,1.000000,1.000000,0.967708,1.0,1.0,1.0,1.000000,0.903125
3,0.545062,0.497429,6.751336e-01,0.000000,0.665761,0.909692,0.510717,0.509764,0.580956,0.747439,...,1.000000,1.0,0.905978,0.905978,0.962391,1.0,1.0,1.0,0.943587,0.924782
4,0.713286,0.681164,7.870434e-01,0.665761,0.000000,0.962701,0.665231,0.740839,0.727552,0.944547,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.905789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1678,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1679,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1680,0.952817,0.921701,1.000000e+00,0.943587,1.000000,1.000000,0.948502,0.917967,0.942640,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.000000,1.000000
1681,0.952817,0.921701,9.031249e-01,0.924782,0.905789,1.000000,0.948502,1.000000,0.928300,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.000000

In [35]:
similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(5).index

In [36]:
similar_input_item

Index([34, 77, 246, 1030, 794], dtype='int64')

In [37]:
similar_item_input=list(similar_input_item)

In [38]:
similar_item_userid_list=[]
for sim_item in similar_item_input:
    sim=list(ratings[ratings['user_id']==sim_item]['movie_id'])
    similar_item_userid_list.append(sim)

In [39]:
similar_item_userid_list

[[312,
  242,
  690,
  310,
  259,
  299,
  245,
  332,
  329,
  286,
  1024,
  324,
  294,
  292,
  990,
  289,
  898,
  899,
  288,
  991],
 [484,
  518,
  172,
  474,
  91,
  195,
  238,
  168,
  125,
  23,
  498,
  431,
  153,
  4,
  181,
  179,
  176,
  276,
  50,
  265,
  174,
  210,
  69,
  405,
  523,
  1028,
  52,
  144,
  778,
  89,
  483,
  357,
  100,
  133,
  201,
  511,
  97,
  56,
  268,
  250,
  215,
  209,
  127,
  641,
  246,
  15,
  175,
  455,
  833,
  31,
  252,
  25,
  132,
  1,
  154,
  96,
  173,
  28,
  519,
  527,
  121,
  156,
  199,
  192,
  636,
  98,
  191,
  134,
  222,
  183,
  42,
  228],
 [201,
  919,
  416,
  94,
  561,
  409,
  665,
  721,
  239,
  425,
  1218,
  68,
  82,
  8,
  406,
  816,
  728,
  184,
  121,
  596,
  80,
  423,
  356,
  202,
  578,
  98,
  294,
  1073,
  215,
  196,
  426,
  849,
  99,
  284,
  109,
  802,
  17,
  410,
  568,
  368,
  100,
  451,
  231,
  840,
  385,
  675,
  720,
  541,
  469,
  1101,
  1,
  588,
  895,
  719,
  161,
  236,
  932,
  145,
  547,
  29,
  470,
  402,
  369,
  289,
  403,
  260,
  1222,
  151,
  83,
  195,
  585,
  230,
  117,
  628,
  55,
  790,
  3,
  232,
  930,
  176,
  743,
  265,
  1232,
  101,
  831,
  758,
  250,
  38,
  444,
  210,
  25,
  420,
  41,
  393,
  138,
  652,
  211,
  412,
  475,
  853,
  238,
  441,
  567,
  12,
  208,
  95,
  746,
  679,
  24,
  1052,
  216,
  77,
  413,
  572,
  1411,
  993,
  254,
  81,
  118,
  1139,
  173,
  92,
  1028,
  559,
  198,
  235,
  981,
  401,
  1044,
  288,
  219,
  132,
  1228,
  633,
  97,
  741,
  11,
  228,
  576,
  178,
  798,
  204,
  431,
  411,
  1089,
  748,
  404,
  181,
  172,
  672,
  550,
  67,
  1188,
  96,
  841,
  185,
  809,
  69,
  432,
  223,
  570,
  724,
  1039,
  174,
  1135,
  227,
  133,
  616,
  447,
  257,
  941,
  155,
  651,
  418,
  50,
  1220,
  827,
  252,
  56,
  735,
  597,
  111,
  164,
  765,
  226,
  433,
  175,
  477,
  240,
  658,
  384,
  159,
  66,
  739,
  158],
 [],
 [242,
  887,
  118,
  475,
  50,
  238,
  514,
  221,
  557,
  24,
  847,
  751,
  1,
  269,
  248,
  150,
  420,
  127,
  275,
  181,
  286,
  14,
  116,
  109,
  285,
  473,
  224,
  455,
  137,
  273,
  13,
  1251,
  19,
  257,
  187,
  936,
  249,
  515,
  100]]

In [40]:
import itertools
similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))

In [41]:
len(similar_item_userid_single_list)

326

In [42]:
Unique_userid_similar_item=set(similar_item_userid_single_list)

In [43]:
input_item_watched_userid=list(ratings[ratings['user_id']==input_item]['user_id'].values)

In [44]:
input_item_watched_userid

[np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34)]

In [45]:
recom=[]
for per_id in Unique_userid_similar_item:
    if(per_id in input_item_watched_userid):
        pass
    else:
        recom.append(per_id)

In [46]:
len(recom)

279

In [47]:
sorted(recom)

[1,
 3,
 4,
 8,
 11,
 12,
 13,
 14,
 15,
 17,
 19,
 23,
 24,
 25,
 28,
 29,
 31,
 38,
 41,
 42,
 50,
 52,
 55,
 56,
 66,
 67,
 68,
 69,
 77,
 80,
 81,
 82,
 83,
 89,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 109,
 111,
 116,
 117,
 118,
 121,
 125,
 127,
 132,
 133,
 134,
 137,
 138,
 144,
 145,
 150,
 151,
 153,
 154,
 155,
 156,
 158,
 159,
 161,
 164,
 168,
 172,
 173,
 174,
 175,
 176,
 178,
 179,
 181,
 183,
 184,
 185,
 187,
 191,
 192,
 195,
 196,
 198,
 199,
 201,
 202,
 204,
 208,
 209,
 210,
 211,
 215,
 216,
 219,
 221,
 222,
 223,
 224,
 226,
 227,
 228,
 230,
 231,
 232,
 235,
 236,
 238,
 239,
 240,
 242,
 245,
 246,
 248,
 249,
 250,
 252,
 254,
 257,
 259,
 260,
 265,
 268,
 269,
 273,
 275,
 276,
 284,
 285,
 286,
 288,
 289,
 292,
 294,
 299,
 310,
 312,
 324,
 329,
 332,
 356,
 357,
 368,
 369,
 384,
 385,
 393,
 401,
 402,
 403,
 404,
 405,
 406,
 409,
 410,
 411,
 412,
 413,
 416,
 418,
 420,
 423,
 425,
 426,
 431,
 432,
 433,
 441,
 444,
 447,
 451,
 455,
 469,
 470,
 473,
 474,
 475,
 477,
 483,
 484,
 498,
 511,
 514,
 515,
 518,
 519,
 523,
 527,
 541,
 547,
 550,
 557,
 559,
 561,
 567,
 568,
 570,
 572,
 576,
 578,
 585,
 588,
 596,
 597,
 616,
 628,
 633,
 636,
 641,
 651,
 652,
 658,
 665,
 672,
 675,
 679,
 690,
 719,
 720,
 721,
 724,
 728,
 735,
 739,
 741,
 743,
 746,
 748,
 751,
 758,
 765,
 778,
 790,
 798,
 802,
 809,
 816,
 827,
 831,
 833,
 840,
 841,
 847,
 849,
 853,
 887,
 895,
 898,
 899,
 919,
 930,
 932,
 936,
 941,
 981,
 990,
 991,
 993,
 1024,
 1028,
 1039,
 1044,
 1052,
 1073,
 1089,
 1101,
 1135,
 1139,
 1188,
 1218,
 1220,
 1222,
 1228,
 1232,
 1251,
 1411]

In [48]:
sorted(Unique_userid_similar_item)

[1,
 3,
 4,
 8,
 11,
 12,
 13,
 14,
 15,
 17,
 19,
 23,
 24,
 25,
 28,
 29,
 31,
 38,
 41,
 42,
 50,
 52,
 55,
 56,
 66,
 67,
 68,
 69,
 77,
 80,
 81,
 82,
 83,
 89,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 109,
 111,
 116,
 117,
 118,
 121,
 125,
 127,
 132,
 133,
 134,
 137,
 138,
 144,
 145,
 150,
 151,
 153,
 154,
 155,
 156,
 158,
 159,
 161,
 164,
 168,
 172,
 173,
 174,
 175,
 176,
 178,
 179,
 181,
 183,
 184,
 185,
 187,
 191,
 192,
 195,
 196,
 198,
 199,
 201,
 202,
 204,
 208,
 209,
 210,
 211,
 215,
 216,
 219,
 221,
 222,
 223,
 224,
 226,
 227,
 228,
 230,
 231,
 232,
 235,
 236,
 238,
 239,
 240,
 242,
 245,
 246,
 248,
 249,
 250,
 252,
 254,
 257,
 259,
 260,
 265,
 268,
 269,
 273,
 275,
 276,
 284,
 285,
 286,
 288,
 289,
 292,
 294,
 299,
 310,
 312,
 324,
 329,
 332,
 356,
 357,
 368,
 369,
 384,
 385,
 393,
 401,
 402,
 403,
 404,
 405,
 406,
 409,
 410,
 411,
 412,
 413,
 416,
 418,
 420,
 423,
 425,
 426,
 431,
 432,
 433,
 441,
 444,
 447,
 451,
 455,
 469,
 470,
 473,
 474,
 475,
 477,
 483,
 484,
 498,
 511,
 514,
 515,
 518,
 519,
 523,
 527,
 541,
 547,
 550,
 557,
 559,
 561,
 567,
 568,
 570,
 572,
 576,
 578,
 585,
 588,
 596,
 597,
 616,
 628,
 633,
 636,
 641,
 651,
 652,
 658,
 665,
 672,
 675,
 679,
 690,
 719,
 720,
 721,
 724,
 728,
 735,
 739,
 741,
 743,
 746,
 748,
 751,
 758,
 765,
 778,
 790,
 798,
 802,
 809,
 816,
 827,
 831,
 833,
 840,
 841,
 847,
 849,
 853,
 887,
 895,
 898,
 899,
 919,
 930,
 932,
 936,
 941,
 981,
 990,
 991,
 993,
 1024,
 1028,
 1039,
 1044,
 1052,
 1073,
 1089,
 1101,
 1135,
 1139,
 1188,
 1218,
 1220,
 1222,
 1228,
 1232,
 1251,
 1411]

In [49]:
sorted(input_item_watched_userid)

[np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34),
 np.int64(34)]

In [50]:
list(set(Unique_userid_similar_item)&set(input_item_watched_userid))

[]

In [51]:
item_pred=pd.DataFrame(item_prediction)

In [52]:
item_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
1,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
2,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
3,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
4,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
939,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
940,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
941,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
942,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

In [53]:
item_pred_Trans=item_pred.T

In [54]:
item_pred_Trans[30]

0       0.076017
1       0.082448
2       0.081734
3       0.075547
4       0.083495
          ...
1677    0.082396
1678    0.082396
1679    0.082396
1680    0.083094
1681    0.083983
Name: 30, Length: 1682, dtype: float64

In [55]:
gg=item_pred_Trans[30]

In [56]:
g=pd.DataFrame(gg)

In [57]:
s=g.T

In [58]:
s[187].values >=0.4

array([False])

In [59]:
highest_Rated=[]
input_item_pre=pd.DataFrame(item_pred_Trans[input_item])
input_item_pred=input_item_pre.T
for re in recom:
    value=input_item_pred[re].values
    if(value>=1):
        highest_Rated.append(re)

In [60]:
len(highest_Rated)

0

In [61]:
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,
encoding='latin-1')

In [62]:
movie_title=[]
for userid in highest_Rated:
    mov=items[items['movie id']==userid]['movie title'].values
    movie_title.append(mov)

In [63]:
movie_title

[]

In [64]:
movie_title_list=[]
for m in movie_title:
    print(m)
    mv=list(m)
    movie_title_list.append(mv)

In [65]:
import itertools
Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))

In [66]:
Final_Recommend_movie

[]

In [67]:
list(set(recom)&set(input_item_watched_userid))

[]

In [107]:
def itembased(input_item, item_similarity, item_predictions,
              similar_item_count, thres):

    input_index = input_item - 1

    item_sim_table = pd.DataFrame(item_similarity)

    similar_item_indexes = (
        item_sim_table[input_index]
        .sort_values(ascending=False)
        .iloc[1:similar_item_count + 1]
        .index
        .tolist()
    )

    similar_movie_ids = [
        index + 1
        for index in similar_item_indexes
    ]
    item_pred_df = pd.DataFrame(item_predictions)

    recommended_movie_ids = []

    for movie_id in similar_movie_ids:

        movie_index = movie_id - 1

        # Average predicted rating for this movie
        predicted_score = item_pred_df.iloc[:, movie_index].mean()

        if predicted_score >= thres:
            recommended_movie_ids.append(movie_id)
    i_cols = [
        'movie id',
        'movie title',
        'release date',
        'video release date',
        'IMDb URL',
        'unknown',
        'Action',
        'Adventure',
        'Animation',
        "Children's",
        'Comedy',
        'Crime',
        'Documentary',
        'Drama',
        'Fantasy',
        'Film-Noir',
        'Horror',
        'Musical',
        'Mystery',
        'Romance',
        'Sci-Fi',
        'Thriller',
        'War',
        'Western'
    ]

    final_recommend_movies = (
        items[
            items['movie id'].isin(recommended_movie_ids)
        ]['movie title']
        .tolist()
    )

    print("Input Movie ID:", input_item)

    print(
        "Similar Movie IDs:",
        similar_movie_ids
    )

    print(
        "Recommended Movie IDs:",
        recommended_movie_ids
    )

    print(
        "Recommended Movies:",
        final_recommend_movies
    )


    return final_recommend_movies

In [108]:
Recommended_movie = itembased(
    29,
    item_similarity,
    item_pred,
    20,
    0.3
)

Input Movie ID: 29
Similar Movie IDs: [1319, 1515, 1272, 1281, 1293, 1294, 1507, 1505, 1295, 1302, 1304, 1309, 1310, 1320, 1257, 1323, 711, 1325, 701, 1326]
Recommended Movie IDs: []
Recommended Movies: []